name: CI/CD

on:
  push:
    branches:
      - main # Substitua 'main' pelo nome da sua branch principal
      - feature/start-project # Substitua 'main' pelo nome da sua branch principal

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      # - name: Execute Python script to update platformio.ini
      #   run: python update_platformio_ini.py

      - name: Set Build Number in platformio.ini
        run: sed -i "s/\[_BUILD_NUMBER_\]/v0.0.${{ github.run_number }}/g" platformio.ini

      - name: Install PlatformIO Core
        run: |
          pip install platformio
          platformio update

      - name: Build Project
        run: platformio run

      - name: Rename firmware.bin files
        run: |
          for file in $(find .pio/build/**/ -name 'firmware.bin'); do
            version=$(echo ${{ github.run_number }})
            env=$(basename $(dirname "$file"))
            new_name="OrcaOne_${env}_v0.0.$version.bin"
            mv "$file" "$(dirname "$file")/$new_name"
          done
          chmod +r .pio/build/**/OrcaOne*.bin
          ls .pio/build/**/OrcaOne*.bin

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
          body: |
            Release automatically generated by CI/CD workflow.

      - name: Upload Binaries
        id: upload_binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: .pio/build/**/OrcaOne*.bin
